apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-deployment
    spec:
      containers:
      - image: redis/redis-stack:latest
        name: redis-container
        ports:
        - containerPort: 6379
          name: redis-srv-port
        - containerPort: 8002
          name: redis-ui-port
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server-service
spec:
  selector:
    app: redis-deployment 
  ports:
  - name: redis-server-service-6379
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ui-service
spec:
  type: NodePort
  selector:
    app: redis-deployment 
  ports:
  - name: redis-ui-service-8002
    protocol: TCP
    port: 8002
    targetPort: 8001